"""Generate the RSA-2048 keypair that signs BusyLight firmware updates.

Outputs:
  scripts/private_key.pem         RSA private key (KEEP SECRET — gitignored).
  scripts/public_key.pem          RSA public key in PEM (for humans).
  include/signing_pubkey.h        public key embedded as a DER byte
                                   array, included by the firmware so OTA
                                   uploads can be verified on-device.

Run once when you set up the project. Re-running rotates the key, which
breaks updates signed by the previous private key — handle with care.

Requires the `cryptography` Python package:

    pip install cryptography
"""

from __future__ import annotations

import sys
import textwrap
from pathlib import Path

try:
    from cryptography.hazmat.primitives import serialization
    from cryptography.hazmat.primitives.asymmetric import rsa
except ImportError:
    print(
        "ERROR: the 'cryptography' Python package is required.\n"
        "       pip install cryptography",
        file=sys.stderr,
    )
    raise SystemExit(2)


HERE = Path(__file__).resolve().parent
FIRMWARE_DIR = HERE.parent
PRIVATE_PEM = HERE / "private_key.pem"
PUBLIC_PEM = HERE / "public_key.pem"
HEADER = FIRMWARE_DIR / "include" / "signing_pubkey.h"


def build_header_text(key_bytes: str) -> str:
    return (
        "// SPDX-License-Identifier: MIT\n"
        "//\n"
        "// Generated by firmware/scripts/gen_signing_key.py - DO NOT EDIT.\n"
        "// Public half of the RSA-2048 keypair that signs OTA firmware\n"
        "// uploads. The matching private key lives in\n"
        "// firmware/scripts/private_key.pem and must NEVER be committed.\n"
        "//\n"
        "// Re-run gen_signing_key.py to rotate. Any firmware signed by an\n"
        "// older private key will then fail OTA verification, so plan the\n"
        "// roll-out carefully.\n"
        "\n"
        "#pragma once\n"
        "\n"
        "#include <stddef.h>\n"
        "#include <stdint.h>\n"
        "\n"
        "// SubjectPublicKeyInfo DER (parsable by mbedtls_pk_parse_public_key).\n"
        "inline const uint8_t kSigningPublicKeyDer[] = {\n"
        f"{key_bytes}\n"
        "};\n"
        "\n"
        "inline constexpr size_t kSigningPublicKeyDerLen ="
        " sizeof(kSigningPublicKeyDer);\n"
    )


def format_byte_array(data: bytes, *, indent: str = "    ", width: int = 12) -> str:
    out: list[str] = []
    for i in range(0, len(data), width):
        chunk = data[i : i + width]
        out.append(indent + ", ".join(f"0x{b:02x}" for b in chunk) + ",")
    return "\n".join(out)


def main() -> int:
    if PRIVATE_PEM.exists():
        print(
            f"Existing keypair at {PRIVATE_PEM.relative_to(FIRMWARE_DIR)}; "
            f"refreshing the embedded header only.\n"
            f"(Delete the .pem files manually if you really want to rotate.)"
        )
        key = serialization.load_pem_private_key(
            PRIVATE_PEM.read_bytes(), password=None
        )
    else:
        print(f"Generating RSA-2048 keypair...")
        key = rsa.generate_private_key(public_exponent=65537, key_size=2048)

        priv_pem = key.private_bytes(
            encoding=serialization.Encoding.PEM,
            format=serialization.PrivateFormat.TraditionalOpenSSL,
            encryption_algorithm=serialization.NoEncryption(),
        )
        pub_pem = key.public_key().public_bytes(
            encoding=serialization.Encoding.PEM,
            format=serialization.PublicFormat.SubjectPublicKeyInfo,
        )
        PRIVATE_PEM.write_bytes(priv_pem)
        PUBLIC_PEM.write_bytes(pub_pem)

    pub_der = key.public_key().public_bytes(
        encoding=serialization.Encoding.DER,
        format=serialization.PublicFormat.SubjectPublicKeyInfo,
    )

    HEADER.parent.mkdir(parents=True, exist_ok=True)
    HEADER.write_text(
        build_header_text(format_byte_array(pub_der)),
        encoding="utf-8",
    )

    print(f"  wrote {PRIVATE_PEM.relative_to(FIRMWARE_DIR)}  (KEEP SECRET, gitignored)")
    print(f"  wrote {PUBLIC_PEM.relative_to(FIRMWARE_DIR)}")
    print(f"  wrote {HEADER.relative_to(FIRMWARE_DIR)}  (embedded by firmware)")
    print()
    print("Next: rebuild and reflash the firmware so the new public key takes effect.")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
